"""
Playlist Resources: an evergreen authority knowledge base.

Four fixed sections of trusted historical/doctrinal sources (papal history,
councils & heresies, trials of the Church, Church Fathers). Each resource
carries a summary + "why it matters" relevance blurb and an optional YouTube
teaching link — the public page shows insight FIRST, then the video CTA
(authority → conversion, never a bare link drop).

Deterministic-first: SEO meta (title/description/keywords) is generated by
pure-Python templates at save time — no AI, no quota, never 402.
"""

import json
import logging

from sqlalchemy.orm import Session

from app.models.db_models import PlaylistResource

logger = logging.getLogger(__name__)

SOURCE_TYPES = ("book", "council", "father", "encyclopedia", "document")
ALLOWED_TAGS = ("papacy", "heresy", "councils", "fathers", "persecution")

SECTIONS: dict[str, str] = {
    "papal-history": "Papal History",
    "heresies-councils": "Heresies & Councils",
    "trials-of-the-church": "Trials of the Church",
    "church-fathers": "Church Fathers",
    "playlist-resources": "Core Teachings",
}


def _safe_url(url: str | None) -> str | None:
    u = (url or "").strip()
    return u if u.lower().startswith(("http://", "https://")) else None


def _seo_for(title: str, category: str, description: str) -> tuple[str, str, list[str]]:
    """Deterministic SEO meta — pure templates, no AI."""
    section = SECTIONS.get(category, "Catholic History")
    seo_title = f"{title} — {section} Explained (Catholic Sources)"[:300]
    base_desc = (description or "").strip().replace("\n", " ")
    seo_description = (
        base_desc[:440] + " Explore this trusted Catholic source and what it reveals."
    )[:500]
    keywords = [
        title.lower(),
        section.lower(),
        "catholic history",
        "early church",
        "catholic sources",
    ]
    return seo_title, seo_description, keywords


def _serialize(r: PlaylistResource) -> dict:
    def _load(raw: str) -> list:
        try:
            v = json.loads(raw or "[]")
            return v if isinstance(v, list) else []
        except (ValueError, TypeError):
            return []

    return {
        "id": r.id,
        "title": r.title,
        "category": r.category,
        "category_label": SECTIONS.get(r.category, r.category),
        "description": r.description,
        "relevance": r.relevance,
        "source_type": r.source_type,
        "source_name": r.source_name,
        "link": _safe_url(r.link),
        "video_url": _safe_url(r.video_url),
        "tags": _load(r.tags),
        "seo_title": r.seo_title,
        "seo_description": r.seo_description,
        "seo_keywords": _load(r.seo_keywords),
        "sort_order": r.sort_order,
        "created_at": r.created_at.isoformat() if r.created_at else None,
    }


def list_resources(db: Session, category: str | None = None) -> list[dict]:
    q = db.query(PlaylistResource)
    if category:
        q = q.filter(PlaylistResource.category == category)
    rows = q.order_by(
        PlaylistResource.category, PlaylistResource.sort_order, PlaylistResource.id
    ).all()
    return [_serialize(r) for r in rows]


def grouped(db: Session) -> list[dict]:
    """Sections in fixed order, each with its resources (empty sections skipped)."""
    all_items = list_resources(db)
    out = []
    for slug, label in SECTIONS.items():
        items = [i for i in all_items if i["category"] == slug]
        if items:
            out.append({"slug": slug, "label": label, "resources": items})
    return out


def get_resource(db: Session, resource_id: int) -> dict | None:
    row = db.get(PlaylistResource, resource_id)
    return _serialize(row) if row else None


def create_resource(
    db: Session,
    *,
    title: str,
    category: str,
    description: str = "",
    relevance: str = "",
    source_type: str = "book",
    source_name: str = "",
    link: str | None = None,
    video_url: str | None = None,
    tags: list[str] | None = None,
    sort_order: int = 0,
) -> dict:
    if category not in SECTIONS:
        raise ValueError(f"Unknown category: {category}")
    if source_type not in SOURCE_TYPES:
        source_type = "book"
    clean_tags = [t for t in (tags or []) if t in ALLOWED_TAGS]
    seo_title, seo_desc, seo_kw = _seo_for(title, category, description)
    row = PlaylistResource(
        title=title.strip()[:300],
        category=category,
        description=(description or "").strip(),
        relevance=(relevance or "").strip(),
        source_type=source_type,
        source_name=(source_name or "").strip()[:300],
        link=_safe_url(link),
        video_url=_safe_url(video_url),
        tags=json.dumps(clean_tags),
        seo_title=seo_title,
        seo_description=seo_desc,
        seo_keywords=json.dumps(seo_kw),
        sort_order=sort_order,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return _serialize(row)


def update_resource(db: Session, resource_id: int, fields: dict) -> dict | None:
    row = db.get(PlaylistResource, resource_id)
    if row is None:
        return None
    if "title" in fields and fields["title"]:
        row.title = str(fields["title"]).strip()[:300]
    if "category" in fields and fields["category"] in SECTIONS:
        row.category = fields["category"]
    for key in ("description", "relevance", "source_name"):
        if key in fields and fields[key] is not None:
            setattr(row, key, str(fields[key]).strip())
    if "source_type" in fields and fields["source_type"] in SOURCE_TYPES:
        row.source_type = fields["source_type"]
    if "link" in fields:
        row.link = _safe_url(fields["link"])
    if "video_url" in fields:
        row.video_url = _safe_url(fields["video_url"])
    if "tags" in fields and isinstance(fields["tags"], list):
        row.tags = json.dumps([t for t in fields["tags"] if t in ALLOWED_TAGS])
    if "sort_order" in fields and fields["sort_order"] is not None:
        try:
            row.sort_order = int(fields["sort_order"])
        except (TypeError, ValueError):
            pass
    # Refresh deterministic SEO meta after any content change.
    row.seo_title, row.seo_description, kw = _seo_for(row.title, row.category, row.description)
    row.seo_keywords = json.dumps(kw)
    db.commit()
    db.refresh(row)
    return _serialize(row)


def delete_resource(db: Session, resource_id: int) -> bool:
    row = db.get(PlaylistResource, resource_id)
    if row is None:
        return False
    db.delete(row)
    db.commit()
    return True


def promote_resource(db: Session, resource_id: int) -> dict | None:
    """Content-engine tie-in: Resource → Topic → Email draft (funnel loop).

    Creates an audience Topic and an EmailQueue draft (draft→approve→send —
    nothing bulk-sends). Additive and idempotent-ish via draft dedup.
    """
    item = get_resource(db, resource_id)
    if item is None:
        return None
    from app.services.topic_service import create_topic
    from app.services.email_queue_service import create_draft

    topic = create_topic(
        db,
        title=f"{item['title']} — what it reveals about the early Church"[:200],
        description=(item["description"] or "")[:500],
        source="playlist_resource",
    )
    body_lines = [
        f"Most people have never read {item['title']} — and it changes everything.",
        "",
        (item["description"] or "").strip(),
        "",
        (item["relevance"] or "").strip(),
        "",
        "I break this down in a short teaching — watch it before you form an opinion.",
    ]
    draft = create_draft(
        db,
        subject=f"What {item['title']} actually says"[:300],
        body="\n".join(l for l in body_lines if l is not None),
        source="playlist_resource",
        topic_id=topic.get("id"),
        video_url=item["video_url"],
    )
    return {
        "ok": True,
        "topic": topic,
        "email_draft_id": draft.id if draft else None,
    }


# ── First-boot seed (5 sections, ministry-specified verified sources) ───────
# Every link verified live (2026-07). Two spec links were dead (404) and were
# replaced with equivalent verified sources: USCCB apostolic-succession page
# → Catholic Answers tract; Catholic Answers "early church" tract → the
# "Pillar of Fire, Pillar of Truth" tract. USCCB and Word on Fire bot-block
# curl (403) but serve browsers normally.

_SEED: list[dict] = [
    # ── Papal History (Vatican, New Advent, Catholic Answers, EWTN) ─────────
    dict(category="papal-history", source_type="document",
         title="Vatican Official Website (Papal Documents)",
         source_name="Vatican Official",
         link="https://www.vatican.va/content/vatican/en.html",
         description="The Holy See's official portal — papal documents, encyclicals, and the recognized line of popes from St. Peter to today.",
         relevance="A single, verifiable chain of succession spanning 2,000 years — test it against history yourself.",
         tags=["papacy"]),
    dict(category="papal-history", source_type="encyclopedia",
         title="Papal History (Catholic Encyclopedia)",
         source_name="New Advent — Catholic Encyclopedia",
         link="https://www.newadvent.org/cathen/12272b.htm",
         description="Scholarly encyclopedia coverage of the popes: their lives, writings, crises, and decisions across the centuries.",
         relevance="Lets you examine papal history with sources, not slogans.",
         tags=["papacy"]),
    dict(category="papal-history", source_type="document",
         title="Papacy & St. Peter",
         source_name="Catholic Answers",
         link="https://www.catholic.com/tract/peter-the-rock",
         description="A clear, sourced walkthrough of Matthew 16 and why the early Christians read 'on this rock' the Catholic way.",
         relevance="Answers the most common objection to the papacy with Scripture and the Fathers.",
         tags=["papacy"]),
    dict(category="papal-history", source_type="document",
         title="Apostolic Succession",
         source_name="Catholic Answers",
         link="https://www.catholic.com/tract/apostolic-succession",
         description="How authority passed from the apostles to today's bishops — documented from the earliest Christian writings.",
         relevance="Shows the papacy is a living, documented office — not a legend.",
         tags=["papacy"]),
    dict(category="papal-history", source_type="document",
         title="Papal Teachings & Documents (EWTN Library)",
         source_name="EWTN Library",
         link="https://www.ewtn.com/catholicism/library",
         description="EWTN's searchable library of papal teachings, Church documents, and Catholic scholarship.",
         relevance="A global Catholic media library where you can read the primary documents yourself.",
         tags=["papacy"]),
    # ── Heresies & Councils (Vatican, New Advent, EWTN, Catholic Answers) ───
    dict(category="heresies-councils", source_type="council",
         title="Ecumenical Councils (Vatican Official)",
         source_name="Vatican Official",
         link="https://www.vatican.va/archive/hist_councils/index.htm",
         description="The Vatican's own archive of the ecumenical councils and their documents.",
         relevance="Traces exactly what the Church taught — and what it rejected — era by era.",
         tags=["councils", "heresy"]),
    dict(category="heresies-councils", source_type="council",
         title="Council of Nicaea (Catholic Encyclopedia)",
         source_name="New Advent — Catholic Encyclopedia",
         link="https://www.newadvent.org/cathen/11044a.htm",
         description="The first ecumenical council (325), which defended Christ's divinity against Arianism and gave us the Nicene Creed.",
         relevance="The creed most Christians still recite came from a Catholic council — centuries before the Bible's table of contents was settled.",
         tags=["councils", "heresy"]),
    dict(category="heresies-councils", source_type="council",
         title="Council of Trent (EWTN)",
         source_name="EWTN Library",
         link="https://www.ewtn.com/catholicism/library/council-of-trent-11498",
         description="The Church's authoritative response to the Reformation: Scripture and Tradition, justification, the sacraments.",
         relevance="Answers, point by point, the exact objections most people still raise today.",
         tags=["councils", "heresy"]),
    dict(category="heresies-councils", source_type="council",
         title="Vatican II Documents (Official Vatican)",
         source_name="Vatican Official",
         link="https://www.vatican.va/archive/hist_councils/ii_vatican_council/index.htm",
         description="The complete documents of the Second Vatican Council (1962–65), straight from the Vatican archive.",
         relevance="Shows the same Church, the same authority, still teaching in living memory.",
         tags=["councils", "papacy"]),
    dict(category="heresies-councils", source_type="encyclopedia",
         title="Catholic Doctrine & Heresies (Catholic Answers)",
         source_name="Catholic Answers",
         link="https://www.catholic.com/",
         description="Apologetics home for the great heresies and how the Church answered each one — tracts, Q&A, and sourced articles.",
         relevance="Most modern objections are ancient heresies with new names — see for yourself.",
         tags=["heresy"]),
    # ── Trials of the Church (New Advent, EWTN, Word on Fire) ───────────────
    dict(category="trials-of-the-church", source_type="encyclopedia",
         title="Church History Overview (Catholic Encyclopedia)",
         source_name="New Advent — Catholic Encyclopedia",
         link="https://www.newadvent.org/cathen/03744a.htm",
         description="A scholarly survey of the Church's history — growth, crises, schisms, and renewal across twenty centuries.",
         relevance="An eyewitness-era record of the Church your history books skipped.",
         tags=["persecution"]),
    dict(category="trials-of-the-church", source_type="document",
         title="Early Church Persecutions (EWTN)",
         source_name="EWTN Library",
         link="https://www.ewtn.com/catholicism/library/early-christian-persecutions-11657",
         description="From Nero to Diocletian: the empire-wide persecutions the early Christians endured rather than deny the faith.",
         relevance="People don't die for something they invented last week.",
         tags=["persecution"]),
    dict(category="trials-of-the-church", source_type="document",
         title="Catholic Historical Articles (Word on Fire)",
         source_name="Word on Fire",
         link="https://www.wordonfire.org/articles/",
         description="Essays and articles on the Church's trials and endurance, from Bishop Barron's Word on Fire ministry.",
         relevance="Every generation predicts the Church's end. Every generation is wrong.",
         tags=["persecution", "heresy"]),
    # ── Church Fathers (New Advent, Vatican, Catholic Answers) ──────────────
    dict(category="church-fathers", source_type="father",
         title="Church Fathers Collection",
         source_name="New Advent — Fathers of the Church",
         link="https://www.newadvent.org/fathers/",
         description="The complete writings of the early Church Fathers — Ignatius, Irenaeus, Augustine, and dozens more, free to read.",
         relevance="If your beliefs are original, they should match these men. Do they?",
         tags=["fathers"]),
    dict(category="church-fathers", source_type="document",
         title="Catechism & Church Teaching (Vatican Archive)",
         source_name="Vatican Official",
         link="https://www.vatican.va/archive/ENG0015/_INDEX.HTM",
         description="The Church's official summary of the faith, on the Vatican's own archive — with the Fathers cited on nearly every page.",
         relevance="See how today's teaching quotes the earliest Christians directly.",
         tags=["fathers"]),
    dict(category="church-fathers", source_type="father",
         title="The Early Church Was the Catholic Church",
         source_name="Catholic Answers",
         link="https://www.catholic.com/tract/pillar-of-fire-pillar-of-truth",
         description="A sourced tract showing the Church the apostles founded — its structure, sacraments, and authority — was recognizably Catholic.",
         relevance="Within one lifetime of the apostles, the Church was already called Catholic.",
         tags=["fathers"]),
    # ── Core Teachings (USCCB, EWTN, Catholic Answers) ──────────────────────
    dict(category="playlist-resources", source_type="document",
         title="Catechism of the Catholic Church (USCCB)",
         source_name="USCCB (U.S. Bishops)",
         link="https://www.usccb.org/catechism-of-the-catholic-church",
         description="The U.S. bishops' edition of the Catechism — the official, complete summary of Catholic teaching.",
         relevance="Don't rely on what critics say the Church teaches — read what it actually teaches.",
         tags=["councils"]),
    dict(category="playlist-resources", source_type="document",
         title="Catholic Teachings Overview (EWTN)",
         source_name="EWTN Library",
         link="https://www.ewtn.com/catholicism/teachings",
         description="EWTN's guided overview of core Catholic teachings — the sacraments, prayer, Scripture, and moral life.",
         relevance="The whole faith, organized so a seeker can start anywhere.",
         tags=["fathers"]),
    dict(category="playlist-resources", source_type="document",
         title="Catholic Questions & Answers (Catholic Answers)",
         source_name="Catholic Answers",
         link="https://www.catholic.com/",
         description="The largest Catholic apologetics resource — direct answers to the questions seekers actually ask.",
         relevance="Every hard question you have has already been asked — and answered with sources.",
         tags=["heresy"]),
]

_VERIFIED_UPGRADE_KEY = "resources_verified_v2"


def apply_verified_source_upgrade(db: Session) -> None:
    """One-time forced upgrade to the ministry-specified verified source set.

    Wipes all rows in the 5 fixed sections and reseeds them from _SEED (every
    link verified live). Runs exactly once — guarded by an AppSetting flag —
    so admin edits made AFTER the upgrade are never overwritten.
    """
    from app.models.db_models import AppSetting

    if db.get(AppSetting, _VERIFIED_UPGRADE_KEY) is not None:
        return
    db.query(PlaylistResource).filter(
        PlaylistResource.category.in_(tuple(SECTIONS.keys()))
    ).delete(synchronize_session=False)
    for i, item in enumerate(_SEED):
        seo_title, seo_desc, seo_kw = _seo_for(
            item["title"], item["category"], item["description"]
        )
        db.add(
            PlaylistResource(
                title=item["title"],
                category=item["category"],
                description=item["description"],
                relevance=item["relevance"],
                source_type=item["source_type"],
                source_name=item["source_name"],
                link=_safe_url(item.get("link")),
                tags=json.dumps(item.get("tags", [])),
                seo_title=seo_title,
                seo_description=seo_desc,
                seo_keywords=json.dumps(seo_kw),
                sort_order=i,
            )
        )
    db.add(AppSetting(key=_VERIFIED_UPGRADE_KEY, value="done"))
    db.commit()
    logger.info(
        "Applied verified-source upgrade: %d resources across %d sections.",
        len(_SEED), len(SECTIONS),
    )


def seed_default_resources(db: Session) -> None:
    """Preload the 5 sections on first boot only (never re-adds after that)."""
    if db.query(PlaylistResource.id).first() is not None:
        return
    for i, item in enumerate(_SEED):
        seo_title, seo_desc, seo_kw = _seo_for(
            item["title"], item["category"], item["description"]
        )
        db.add(
            PlaylistResource(
                title=item["title"],
                category=item["category"],
                description=item["description"],
                relevance=item["relevance"],
                source_type=item["source_type"],
                source_name=item["source_name"],
                link=_safe_url(item.get("link")),
                tags=json.dumps(item.get("tags", [])),
                seo_title=seo_title,
                seo_description=seo_desc,
                seo_keywords=json.dumps(seo_kw),
                sort_order=i,
            )
        )
    db.commit()
    logger.info("Seeded %d default playlist resources.", len(_SEED))
